---
name: Vitest

# yamllint disable-line rule:truthy
on:
  push:
    branches: [beta, main]
    paths:
      - "**.ts"
      - "lovelace_strategy/**"
      - "package.json"
      - "vitest.config.ts"
  pull_request:
    branches: [beta, main]
    paths:
      - "**.ts"
      - "lovelace_strategy/**"
      - "package.json"
      - "vitest.config.ts"

jobs:
  prek:
    runs-on: ubuntu-latest
    name: Prek
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: 🛠️ Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.14"
      - name: 🛠️ Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "lts/iron"
      - name: 📦 Install frontend dependencies
        run: yarn install
      - name: 🔍 Run prek
        uses: j178/prek-action@32e56967b16e522f9009165632be8e0cf7e9b3a5 # v2

  test:
    needs: prek
    name: TypeScript Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "lts/iron"

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests and generate coverage report
        run: yarn test --coverage --coverage.reporter=json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: typescript
          files: ./coverage/coverage-final.json
